{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "sample-nodejs.fullname" . }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /my-app
            pathType: Prefix
            backend:
              service:
                name: {{ include "sample-nodejs.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
